# -*- coding: utf-8 -*-

GENDER_CHOICES = (('M', 'M'),('F', 'F'),)

COUNTRY_CHOICES = (
    ('Brazil', 'Brasil'),
    ('', '---------'),
    ('Afghanistan', 'Afeganistão'),
    ('Albania', 'Albânia'),
    ('Algeria', 'Argélia'),
    ('Andorra', 'Andorra'),
    ('Antigua e Barbuda', 'Antígua e Barbuda'),
    ('Argentina', 'Argentina'),
    ('Armenia', 'Arménia'),
    ('Australia', 'Austrália'),
    ('Austria', 'Áustria'),
    ('Azerbaijan', 'Azerbaijão'),
    ('Bahamas', 'Bahamas'),
    ('Bahrain', 'Bahrain'),
    ('Bangladesh', 'Bangladesh'),
    ('Barbados', 'Barbados'),
    ('Belarus', 'Bielorrússia'),
    ('Belgium', 'Bélgica'),
    ('Belize', 'Belize'),
    ('Benin', 'Benin'),
    ('Bhutan', 'Butão'),
    ('Bolivia', 'Bolívia'),
    ('Bosnia e Herzegovina', 'Bósnia e Herzegovina'),
    ('Botswana', 'Botsuana'),
    ('Brunei', 'Brunei'),
    ('Bulgaria', 'Bulgária'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Burundi', 'Burundi'),
    ('Cambodia', 'Camboja'),
    ('Cameroon', 'Camarões'),
    ('Canada', 'Canadá'),
    ('Cape Verde', 'Cabo Verde'),
    ('Central Africano Republic', 'Central Africano República'),
    ('Chad', 'Chade'),
    ('Chile', 'Chile'),
    ('China', 'China'),
    ('Colombia', 'Colômbia'),
    ('Comoros', 'Comores'),
    ('Congo', 'Congo'),
    ('Costa Rica', 'Costa Rica'),
    ('Côte d\'Ivoire', 'Costa do Marfim'),
    ('Croatia', 'Croácia'),
    ('Cuba', 'Cuba'),
    ('Cyprus', 'Chipre'),
    ('Czech Republic', 'República Checa'),
    ('Denmark', 'Dinamarca'),
    ('Djibouti', 'Djibuti'),
    ('Dominica', 'Dominica'),
    ('Dominican Republic', 'República Dominicana'),
    ('East Timor', 'Timor Leste'),
    ('Ecuador', 'Equador'),
    ('Egypt', 'Egito'),
    ('El Salvador', 'El Salvador'),
    ('Equatorial Guinea', 'Guiné Equatorial'),
    ('Eritrea', 'Eritreia'),
    ('Estonia', 'Estónia'),
    ('Ethiopia', 'Etiópia'),
    ('Fiji', 'Fiji'),
    ('Finland', 'Finlândia'),
    ('France', 'França'),
    ('Gabon', 'Gabão'),
    ('Gambia', 'Gâmbia'),
    ('Georgia', 'Geórgia'),
    ('Germany', 'Alemanha'),
    ('Ghana', 'Gana'),
    ('Greece', 'Grécia'),
    ('Grenada', 'Grenada'),
    ('Guatemala', 'Guatemala'),
    ('Guinea', 'Guiné'),
    ('Guinea-Bissau', 'Guiné-Bissau'),
    ('Guyana', 'Guiana'),
    ('Haiti', 'Haiti'),
    ('Honduras', 'Honduras'),
    ('Hong Kong', 'Hong Kong'),
    ('Hungary', 'Hungria'),
    ('Iceland', 'Islândia'),
    ('India', 'Índia'),
    ('Indonesia', 'Indonésia'),
    ('Iran', 'Irão'),
    ('Iraq', 'Iraque'),
    ('Ireland', 'Irlanda'),
    ('Israel', 'Israel'),
    ('Italy', 'Itália'),
    ('Jamaica', 'Jamaica'),
    ('Japan', 'Japão'),
    ('Jordan', 'Jordânia'),
    ('Kazakhstan', 'Cazaquistão'),
    ('Kenya', 'Quênia'),
    ('Kiribati', 'Kiribati'),
    ('North Korea', 'Coreia do Norte'),
    ('South Korea', 'Coréia do Sul'),
    ('Kuwait', 'Kuwait'),
    ('Kyrgyzstan', 'Quirguistão'),
    ('Laos', 'Laos'),
    ('Latvia', 'Letónia'),
    ('Lebanon', 'Líbano'),
    ('Lesotho', 'Lesoto'),
    ('Liberia', 'Libéria'),
    ('Libya', 'Líbia'),
    ('Liechtenstein', 'Liechtenstein'),
    ('Lithuania', 'Lituânia'),
    ('Luxembourg', 'Luxemburgo'),
    ('Macedonia', 'Macedónia'),
    ('Madagascar', 'Madagascar'),
    ('Malawi', 'Malawi'),
    ('Malaysia', 'Malásia'),
    ('Maldives', 'Maldivas'),
    ('Mali', 'Mali'),
    ('Malta', 'Malta'),
    ('Marshall Islands', 'Ilhas Marshall'),
    ('Mauritania', 'Mauritânia'),
    ('Mauritius', 'Maurícia'),
    ('Mexico', 'México'),
    ('Micronesia', 'Micronésia'),
    ('Moldova', 'Moldávia'),
    ('Monaco', 'Monaco'),
    ('Mongolia', 'Mongólia'),
    ('Montenegro', 'Montenegro'),
    ('Morocco', 'Marrocos'),
    ('Mozambique', 'Moçambique'),
    ('Myanmar', 'Myanmar'),
    ('Namibia', 'Namíbia'),
    ('Nauru', 'Nauru'),
    ('Nepal', 'Nepal'),
    ('Netherlands', 'Holanda'),
    ('New Zealand', 'Nova Zelândia'),
    ('Nicaragua', 'Nicarágua'),
    ('Niger', 'Níger'),
    ('Nigeria', 'Nigéria'),
    ('Norway', 'Noruega'),
    ('Oman', 'Omã'),
    ('Pakistan', 'Paquistão'),
    ('Palau', 'Palau'),
    ('Panama', 'Panamá'),
    ('Papua Nova Guinea', 'Papua-Nova Guiné'),
    ('Paraguay', 'Paraguai'),
    ('Peru', 'Peru'),
    ('Philippines', 'Filipinas'),
    ('Poland', 'Polônia'),
    ('Portugal', 'Portugal'),
    ('Puerto Rico', 'Porto Rico'),
    ('Qatar', 'Qatar'),
    ('Romania', 'Roménia'),
    ('Russia', 'Rússia'),
    ('Rwanda', 'Ruanda'),
    ('Saint Kitts e Nevis', 'Saint Kitts e Nevis'),
    ('Saint Lucia', 'Saint Lucia'),
    ('Saint Vicente e Grenadines', 'São Vicente e Granadinas'),
    ('Samoa', 'Samoa'),
    ('San Marino', 'San Marino'),
    ('Sao Tome e Principe', 'São Tomé e Príncipe'),
    ('Saudi Arabia', 'Arábia Saudita'),
    ('Senegal', 'Senegal'),
    ('Serbia e Montenegro', 'Sérvia e Montenegro'),
    ('Seychelles', 'Seychelles'),
    ('Sierra Leone', 'Serra Leoa'),
    ('Singapore', 'Singapore'),
    ('Slovakia', 'Eslováquia'),
    ('Slovenia', 'Eslovénia'),
    ('Solomon Islands', 'Ilhas Salomão'),
    ('Somalia', 'Somália'),
    ('South Africa', 'África do Sul'),
    ('Spain', 'Espanha'),
    ('Sri Lanka', 'Sri Lanka'),
    ('Sudan', 'Sudão'),
    ('Suriname', 'Suriname'),
    ('Swaziland', 'Suazilândia'),
    ('Sweden', 'Suécia'),
    ('Switzerland', 'Suíça'),
    ('Syria', 'Síria'),
    ('Taiwan', 'Taiwan'),
    ('Tajikistan', 'Tajiquistão'),
    ('Tanzania', 'Tanzânia'),
    ('Thailand', 'Tailândia'),
    ('Togo', 'Togo'),
    ('Tonga', 'Tonga'),
    ('Trinidad e Tobago', 'Trinidad e Tobago'),
    ('Tunisia', 'Tunísia'),
    ('Turkey', 'Turquia'),
    ('Turkmenistan', 'Turquemenistão'),
    ('Tuvalu', 'Tuvalu'),
    ('Uganda', 'Uganda'),
    ('Ukraine', 'Ucrânia'),
    ('United Árabes Emirates', 'Emirados Árabes Unidos'),
    ('United Kingdom', 'Reino Unido'),
    ('United States', 'Estados Unidos'),
    ('Uruguay', 'Uruguai'),
    ('Uzbekistan', 'Uzbequistão'),
    ('Vanuatu', 'Vanuatu'),
    ('Vatican City', 'Vaticano'),
    ('Venezuela', 'Venezuela'),
    ('Vietnam', 'Vietnã'),
    ('Yemen', 'Iémen'),
    ('Zambia', 'Zâmbia'),
    ('Zimbabwe', 'Zimbabwe'),
)
